export const MEAL_TEMPLATES = [
  {
    id: "tmpl-savory-oats-egg",
    name: "Savory Oats + Egg Bowl",
    warmth: "WARM",
    digestion: "GENTLE",
    prep: "QUICK",
    macroBias: "BALANCED",
    tags: ["comforting", "easy-digest", "high-satiety", "iron-friendly"],
    phaseFit: ["MENSTRUAL", "LUTEAL"],
  },
  {
    id: "tmpl-ginger-rice-congee",
    name: "Ginger Rice Congee",
    warmth: "WARM",
    digestion: "GENTLE",
    prep: "BATCH",
    macroBias: "HIGH_CARB",
    tags: ["comforting", "easy-digest", "ginger", "hydrating"],
    phaseFit: ["MENSTRUAL", "FOLLICULAR"],
  },
  {
    id: "tmpl-turkey-quinoa-bowl",
    name: "Turkey Quinoa Bowl",
    warmth: "ROOM",
    digestion: "MODERATE",
    prep: "BATCH",
    macroBias: "HIGH_PROTEIN",
    tags: ["high-protein", "prep-friendly", "fiber"],
    phaseFit: ["FOLLICULAR", "OVULATORY", "LUTEAL"],
  },
  {
    id: "tmpl-lentil-soup-toast",
    name: "Lentil Soup + Toast",
    warmth: "WARM",
    digestion: "GENTLE",
    prep: "BATCH",
    macroBias: "BALANCED",
    tags: ["comforting", "fiber", "iron-friendly", "high-satiety"],
    phaseFit: ["MENSTRUAL", "LUTEAL"],
  },
  {
    id: "tmpl-chicken-sweet-potato",
    name: "Chicken + Sweet Potato Plate",
    warmth: "WARM",
    digestion: "MODERATE",
    prep: "BATCH",
    macroBias: "HIGH_PROTEIN",
    tags: ["high-protein", "complex carbs", "high-satiety"],
    phaseFit: ["FOLLICULAR", "LUTEAL"],
  },
  {
    id: "tmpl-yogurt-berry-granola",
    name: "Yogurt Berry Crunch Bowl",
    warmth: "COLD",
    digestion: "MODERATE",
    prep: "ASSEMBLE",
    macroBias: "BALANCED",
    tags: ["quick", "fresh", "protein"],
    phaseFit: ["FOLLICULAR", "OVULATORY"],
  },
  {
    id: "tmpl-salmon-rice-greens",
    name: "Salmon Rice + Greens",
    warmth: "WARM",
    digestion: "MODERATE",
    prep: "BATCH",
    macroBias: "BALANCED",
    tags: ["omega-3", "high-satiety", "iron-friendly"],
    phaseFit: ["MENSTRUAL", "LUTEAL", "OVULATORY"],
  },
  {
    id: "tmpl-tofu-noodle-stirfry",
    name: "Tofu Noodle Stir-Fry",
    warmth: "WARM",
    digestion: "MODERATE",
    prep: "QUICK",
    macroBias: "HIGH_CARB",
    tags: ["prep-friendly", "colorful produce", "fiber"],
    phaseFit: ["FOLLICULAR", "OVULATORY"],
  },
  {
    id: "tmpl-chia-oat-pudding",
    name: "Chia Oat Pudding",
    warmth: "ROOM",
    digestion: "MODERATE",
    prep: "ASSEMBLE",
    macroBias: "HIGH_FAT",
    tags: ["omega-3", "hydration", "quick"],
    phaseFit: ["FOLLICULAR", "OVULATORY"],
  },
  {
    id: "tmpl-bean-rice-stew",
    name: "Bean + Rice Stew",
    warmth: "WARM",
    digestion: "HEAVY",
    prep: "BATCH",
    macroBias: "HIGH_CARB",
    tags: ["high-satiety", "fiber", "comforting"],
    phaseFit: ["LUTEAL"],
  },
  {
    id: "tmpl-egg-avocado-toast",
    name: "Egg + Avocado Toast",
    warmth: "ROOM",
    digestion: "MODERATE",
    prep: "QUICK",
    macroBias: "BALANCED",
    tags: ["quick", "high-satiety", "protein"],
    phaseFit: ["FOLLICULAR", "OVULATORY", "LUTEAL"],
  },
  {
    id: "tmpl-miso-soba-bowl",
    name: "Miso Soba Bowl",
    warmth: "WARM",
    digestion: "GENTLE",
    prep: "QUICK",
    macroBias: "BALANCED",
    tags: ["hydrating", "easy-digest", "comforting"],
    phaseFit: ["MENSTRUAL", "FOLLICULAR", "LUTEAL"],
  },
  {
    id: "tmpl-trailmix-fruit",
    name: "Trail Mix + Fruit",
    warmth: "ROOM",
    digestion: "MODERATE",
    prep: "ASSEMBLE",
    macroBias: "HIGH_FAT",
    tags: ["quick", "high-satiety", "snack"],
    phaseFit: ["FOLLICULAR", "OVULATORY", "LUTEAL"],
  },
  {
    id: "tmpl-hummus-wrap",
    name: "Hummus Veg Wrap",
    warmth: "ROOM",
    digestion: "MODERATE",
    prep: "ASSEMBLE",
    macroBias: "BALANCED",
    tags: ["fiber", "prep-friendly", "colorful produce"],
    phaseFit: ["FOLLICULAR", "OVULATORY"],
  },
];

export const getTemplatesByPhase = (phase) =>
  MEAL_TEMPLATES.filter((template) => template.phaseFit.includes(phase));
