import type { Recipe } from "../types";

export const sampleRecipes: Recipe[] = [
  {
    id: "breakfast-1",
    name: "Berry chia pudding",
    mealType: "breakfast",
    ingredients: ["chia seeds", "berries", "almond milk"],
    tags: ["antioxidant", "fiber", "gentle"],
    timeMinutes: 10,
    costLevel: "budget",
  },
  {
    id: "breakfast-2",
    name: "Savory egg scramble",
    mealType: "breakfast",
    ingredients: ["eggs", "spinach", "olive oil"],
    tags: ["iron-rich", "comforting"],
    timeMinutes: 15,
    costLevel: "balanced",
  },
  {
    id: "lunch-1",
    name: "Chickpea crunch salad",
    mealType: "lunch",
    ingredients: ["chickpeas", "cucumber", "lemon"],
    tags: ["fresh", "fiber", "bright"],
    timeMinutes: 12,
    costLevel: "budget",
  },
  {
    id: "lunch-2",
    name: "Salmon grain bowl",
    mealType: "lunch",
    ingredients: ["salmon", "brown rice", "spinach"],
    tags: ["omega-3", "protein"],
    timeMinutes: 20,
    costLevel: "premium",
  },
  {
    id: "dinner-1",
    name: "Ginger tofu stir-fry",
    mealType: "dinner",
    ingredients: ["tofu", "ginger", "bell pepper"],
    tags: ["ginger", "bright", "protein"],
    timeMinutes: 25,
    costLevel: "balanced",
  },
  {
    id: "dinner-2",
    name: "Roasted veggie tray bake",
    mealType: "dinner",
    ingredients: ["sweet potato", "broccoli", "olive oil"],
    tags: ["comforting", "complex-carb"],
    timeMinutes: 35,
    costLevel: "budget",
  },
  {
    id: "snack-1",
    name: "Apple almond butter",
    mealType: "snack",
    ingredients: ["apple", "almond butter"],
    tags: ["fiber", "comforting"],
    timeMinutes: 5,
    costLevel: "budget",
  },
  {
    id: "snack-2",
    name: "Pumpkin seed trail mix",
    mealType: "snack",
    ingredients: ["pumpkin seeds", "dried cherries"],
    tags: ["magnesium", "stable-energy"],
    timeMinutes: 4,
    costLevel: "budget",
  },
  {
    id: "lunch-3",
    name: "Miso veggie soup",
    mealType: "lunch",
    ingredients: ["miso", "bok choy", "mushrooms"],
    tags: ["gentle", "warming"],
    timeMinutes: 18,
    costLevel: "budget",
  },
  {
    id: "dinner-3",
    name: "Lentil kale stew",
    mealType: "dinner",
    ingredients: ["lentils", "kale", "carrot"],
    tags: ["iron-rich", "warming"],
    timeMinutes: 30,
    costLevel: "budget",
  },
];
